### ISSUE TITLE
Sensitive info is public

### ISSUE THREAD

**Issue by joeyfigaro** [martin-juul/snatch#16]
Hey @martin-juul – was digging around for firebase storage snippets and came across your work here. Just a heads up that your [google service info is public](https://github.com/martin-juul/snatch/blob/8a638fb600b8c7e00efd7cf3ed2985bd38eb5eb7/packages/firebase/config/GoogleService-Info.plist), in case you weren't aware. 💪🏻

**Comment by martin-juul** [comment]
Thank you for notifying. Didn't realize the problem.
